In [15]:
import pandas as pd

In [35]:
df = pd.read_csv('data_sp500.csv')

In [36]:
df.head()

,obs_main,exch_main,common,primary_sec,permno,date,id,excntry,eom,size_grp,...,betadown_252d,bidaskhl_21d,corr_1260d,betabab_1260d,rmax5_rvol_21d,age,qmj,qmj_prof,qmj_growth,qmj_safety
0,1,1,1,1,10104,2010-01-29,10104,USA,2010-01-31,mega,...,0.695554,0.006462,0.639061,0.760289,0.639375,301,0.684386,1.574106,-1.059532,0.876409
1,1,1,1,1,10104,2010-02-26,10104,USA,2010-02-28,mega,...,0.641482,0.008757,0.641327,0.784230,1.017473,302,0.676528,1.574487,-1.067895,0.853330
2,1,1,1,1,10104,2010-03-31,10104,USA,2010-03-31,mega,...,0.702626,0.006310,0.640097,0.767558,0.837864,303,0.721129,1.547676,-1.081173,0.964827
3,1,1,1,1,10104,2010-04-30,10104,USA,2010-04-30,mega,...,0.804228,0.006173,0.638874,0.790186,0.629478,304,0.722896,1.524835,-1.145032,0.941935
4,1,1,1,1,10104,2010-05-28,10104,USA,2010-05-31,mega,...,0.932947,0.007175,0.652172,0.819710,1.324357,305,0.682955,1.524512,-1.154701,0.885675

In [37]:
df['ret']

0       -0.057888
1        0.068951
2        0.043002
3        0.008071
4       -0.127477
           ...
81611   -0.077390
81612    0.221942
81613   -0.045025
81614    0.381469
81615    0.170008
Name: ret, Length: 81616, dtype: float64

In [38]:
df.sort_values('date', inplace=True)

In [39]:
df.head()

,obs_main,exch_main,common,primary_sec,permno,date,id,excntry,eom,size_grp,...,betadown_252d,bidaskhl_21d,corr_1260d,betabab_1260d,rmax5_rvol_21d,age,qmj,qmj_prof,qmj_growth,qmj_safety
0,1,1,1,1,10104,2010-01-29,10104,USA,2010-01-31,mega,...,0.695554,0.006462,0.639061,0.760289,0.639375,301,0.684386,1.574106,-1.059532,0.876409
45325,1,1,1,1,67029,2010-01-29,67029,USA,2010-01-31,micro,...,0.747078,0.008188,0.380739,0.756918,0.668567,349,0.741227,0.854471,0.843226,-0.214149
76400,1,1,1,1,91068,2010-01-29,91068,USA,2010-01-31,large,...,0.716928,0.012760,0.485772,0.760323,1.521496,121,1.708443,1.412913,1.596631,1.556960
14283,1,1,1,1,17750,2010-01-29,17750,USA,2010-01-31,mega,...,0.495061,0.006401,0.556770,0.437811,0.597579,969,1.402235,1.421317,0.916550,0.774288
45145,1,1,1,1,66800,2010-01-29,66800,USA,2010-01-31,large,...,3.618546,0.008680,0.423440,2.662480,0.165031,457,-1.650685,-1.523685,-1.577383,-1.146190

In [40]:
print(df['date'].dtype)
print(df.dtypes)

object
obs_main         int64
exch_main        int64
common           int64
primary_sec      int64
permno           int64
                ...
age              int64
qmj            float64
qmj_prof       float64
qmj_growth     float64
qmj_safety     float64
Length: 170, dtype: object

In [41]:
df['date'] = pd.to_datetime(df['date'], errors='coerce')

In [44]:
print(df['date'].dtype)

datetime64[ns]

In [45]:
ff = pd.read_csv('FF5.csv')

In [46]:
ff.head()

       Date  Mkt-RF   SMB   HML   RMW   CMA     RF
0  19630701   -0.67  0.02 -0.35  0.03  0.13  0.012
1  19630702    0.79 -0.28  0.28 -0.08 -0.21  0.012
2  19630703    0.63 -0.18 -0.10  0.13 -0.25  0.012
3  19630705    0.40  0.09 -0.28  0.07 -0.30  0.012
4  19630708   -0.63  0.07 -0.20 -0.27  0.06  0.012

In [48]:
ff['Date'] = pd.to_datetime(ff['Date'], format='%Y%m%d', errors='coerce')

In [49]:
ff.head()

        Date  Mkt-RF   SMB   HML   RMW   CMA     RF
0 1963-07-01   -0.67  0.02 -0.35  0.03  0.13  0.012
1 1963-07-02    0.79 -0.28  0.28 -0.08 -0.21  0.012
2 1963-07-03    0.63 -0.18 -0.10  0.13 -0.25  0.012
3 1963-07-05    0.40  0.09 -0.28  0.07 -0.30  0.012
4 1963-07-08   -0.63  0.07 -0.20 -0.27  0.06  0.012

In [50]:
print(ff['Date'].dtype)

datetime64[ns]

In [51]:
ff.rename(columns={'Date': 'date'}, inplace=True)

In [52]:
df = df.merge(ff, on='date', how='left', suffixes=('', '_ff'))

df.head()

,obs_main,exch_main,common,primary_sec,permno,date,id,excntry,eom,size_grp,...,qmj,qmj_prof,qmj_growth,qmj_safety,Mkt-RF,SMB,HML,RMW,CMA,RF
0,1,1,1,1,10104,2010-01-29,10104,USA,2010-01-31,mega,...,0.684386,1.574106,-1.059532,0.876409,-0.97,-0.08,-0.42,-0.2,0.18,0.0
1,1,1,1,1,67029,2010-01-29,67029,USA,2010-01-31,micro,...,0.741227,0.854471,0.843226,-0.214149,-0.97,-0.08,-0.42,-0.2,0.18,0.0
2,1,1,1,1,91068,2010-01-29,91068,USA,2010-01-31,large,...,1.708443,1.412913,1.596631,1.556960,-0.97,-0.08,-0.42,-0.2,0.18,0.0
3,1,1,1,1,17750,2010-01-29,17750,USA,2010-01-31,mega,...,1.402235,1.421317,0.916550,0.774288,-0.97,-0.08,-0.42,-0.2,0.18,0.0
4,1,1,1,1,66800,2010-01-29,66800,USA,2010-01-31,large,...,-1.650685,-1.523685,-1.577383,-1.146190,-0.97,-0.08,-0.42,-0.2,0.18,0.0

In [54]:
df['ew_ret'] = df.groupby('date')['ret'].transform('mean')

In [55]:
df.head()

,obs_main,exch_main,common,primary_sec,permno,date,id,excntry,eom,size_grp,...,qmj_prof,qmj_growth,qmj_safety,Mkt-RF,SMB,HML,RMW,CMA,RF,ew_ret
0,1,1,1,1,10104,2010-01-29,10104,USA,2010-01-31,mega,...,1.574106,-1.059532,0.876409,-0.97,-0.08,-0.42,-0.2,0.18,0.0,-0.0247
1,1,1,1,1,67029,2010-01-29,67029,USA,2010-01-31,micro,...,0.854471,0.843226,-0.214149,-0.97,-0.08,-0.42,-0.2,0.18,0.0,-0.0247
2,1,1,1,1,91068,2010-01-29,91068,USA,2010-01-31,large,...,1.412913,1.596631,1.556960,-0.97,-0.08,-0.42,-0.2,0.18,0.0,-0.0247
3,1,1,1,1,17750,2010-01-29,17750,USA,2010-01-31,mega,...,1.421317,0.916550,0.774288,-0.97,-0.08,-0.42,-0.2,0.18,0.0,-0.0247
4,1,1,1,1,66800,2010-01-29,66800,USA,2010-01-31,large,...,-1.523685,-1.577383,-1.146190,-0.97,-0.08,-0.42,-0.2,0.18,0.0,-0.0247

In [56]:
df['ew_ret_excess'] = df['ew_ret'] - df['RF']

In [57]:
df.head()

,obs_main,exch_main,common,primary_sec,permno,date,id,excntry,eom,size_grp,...,qmj_growth,qmj_safety,Mkt-RF,SMB,HML,RMW,CMA,RF,ew_ret,ew_ret_excess
0,1,1,1,1,10104,2010-01-29,10104,USA,2010-01-31,mega,...,-1.059532,0.876409,-0.97,-0.08,-0.42,-0.2,0.18,0.0,-0.0247,-0.0247
1,1,1,1,1,67029,2010-01-29,67029,USA,2010-01-31,micro,...,0.843226,-0.214149,-0.97,-0.08,-0.42,-0.2,0.18,0.0,-0.0247,-0.0247
2,1,1,1,1,91068,2010-01-29,91068,USA,2010-01-31,large,...,1.596631,1.556960,-0.97,-0.08,-0.42,-0.2,0.18,0.0,-0.0247,-0.0247
3,1,1,1,1,17750,2010-01-29,17750,USA,2010-01-31,mega,...,0.916550,0.774288,-0.97,-0.08,-0.42,-0.2,0.18,0.0,-0.0247,-0.0247
4,1,1,1,1,66800,2010-01-29,66800,USA,2010-01-31,large,...,-1.577383,-1.146190,-0.97,-0.08,-0.42,-0.2,0.18,0.0,-0.0247,-0.0247

In [58]:
df.rename(columns={'Mkt-RF': 'mkt-rf', 'SMB': 'smb', 'HML': 'hml', 'RMW': 'rmw', 'CMA': 'cma', 'RF': 'rf'}, inplace=True)

In [59]:
df.to_csv('data_sp500_ff.csv', index=False)